name: ci

on:
  - push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.2.19
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.17
      - name: Run compile
        run: sbt compile
      - name: Run test
        run: sbt test
